import {useCallback,useEffect,useRef,useState} from 'react';import {useNavigate} from 'react-router-dom';import {AnimatePresence,motion} from 'framer-motion';import {BriefcaseBusiness,Building2,FileSpreadsheet,Users} from 'lucide-react';import {useAuth} from '@/contexts/AuthContext';import {SCRIPT,type Line} from './data/script';import {EVIDENCE,TEAMS,type EvidenceId,type TeamId} from './data/case';import {newRun,evaluate,type Link,type RewardRun} from './engine/model';import {clearRun,loadRun,saveRun} from './engine/persistence';import {claimOwnership,mayWrite,releaseOwnership,takeOwnership} from './engine/ownership';import {ScenePlayer} from './components/ScenePlayer';import {DialoguePanel} from './components/DialoguePanel';import {ActionButton,GameHud,Panel,PauseLayer,ReplayButton} from './components/Ui';import {CaseFile} from './components/CaseFile';import {Workbench} from './components/Workbench';import {Recommendation} from './components/Recommendation';import {Meeting} from './components/Meeting';import impLogo from '@/assets/brand/imp-logo.webp';import analystMark from '@/assets/brand/the-analyst-mark.png';import './reward-decision.css';
const phaseDialogue:Partial<Record<RewardRun['phase'],keyof typeof SCRIPT>>={celebration:'D01',debate:'D02',briefing:'D03',sales:'D04',hr:'D05'};
const phaseShot:Partial<Record<RewardRun['phase'],string>>={cover:'A00',celebration:'A02',debate:'A04',briefing:'A07',hub:'A09',sales:'A11',hr:'A13',workbench:'A16',recommendation:'A17',meeting:'A18',resolution:'A21',debrief:'A25'};
export default function RewardDecisionGame(){const {user,profile}=useAuth();const navigate=useNavigate();const uid=user?.id??'';const [run,setRun]=useState<RewardRun>(()=>loadRun(uid)??newRun(uid));const [fileOpen,setFileOpen]=useState(false);const [otherTab,setOtherTab]=useState(false);const [storageOk,setStorageOk]=useState(true);const runRef=useRef(run);runRef.current=run;
const commit=useCallback((fn:(r:RewardRun)=>RewardRun)=>setRun(prev=>{const next=fn(prev);if(mayWrite()&&next.phase!=='cover')setStorageOk(saveRun(next));return next}),[]);
useEffect(()=>{if(!uid)return;setOtherTab(!claimOwnership(uid,run.runId,()=>{setOtherTab(true);setRun(r=>({...r,paused:true}))}));return releaseOwnership},[uid,run.runId]);
useEffect(()=>{const pause=()=>{if(document.visibilityState==='hidden'){const next={...runRef.current,paused:true};setRun(next);if(mayWrite())saveRun(next)}};document.addEventListener('visibilitychange',pause);window.addEventListener('pagehide',pause);return()=>{document.removeEventListener('visibilitychange',pause);window.removeEventListener('pagehide',pause)}},[]);
const setPhase=(phase:RewardRun['phase'],shotId=phaseShot[phase]??run.shotId)=>commit(r=>({...r,phase,shotId,dialogueIndex:0,visibleGraphemes:0,paused:false}));
const activeKey=phaseDialogue[run.phase];const lines=activeKey?SCRIPT[activeKey]:null;const line=lines?.[run.dialogueIndex];const finishDialogue=()=>{if(run.phase==='celebration')setPhase('debate','A04');else if(run.phase==='debate')setPhase('briefing','A07');else if(run.phase==='briefing')setPhase('hub','A09');else commit(r=>({...r,dialogueIndex:(lines?.length??1),visibleGraphemes:0}))};
const advanceDialogue=()=>{if(!lines)return;if(run.dialogueIndex+1<lines.length){const next=run.dialogueIndex+1;const shot=run.phase==='debate'&&next===3?'A05':run.phase==='briefing'&&next===5?'A08':run.shotId;commit(r=>({...r,dialogueIndex:next,visibleGraphemes:0,shotId:shot}))}else finishDialogue()};
const visit=(phase:'sales'|'hr')=>commit(r=>({...r,phase,shotId:phaseShot[phase]??r.shotId,dialogueIndex:r.visited.includes(phase)?99:0,visibleGraphemes:0,visited:r.visited.includes(phase)?r.visited:[...r.visited,phase]}));
const saveDoc=(doc:string)=>commit(r=>({...r,collectedDocs:r.collectedDocs.includes(doc)?r.collectedDocs:[...r.collectedDocs,doc]}));
const start=()=>{const next=newRun(uid);setRun({...next,phase:'celebration',shotId:'A02'});setOtherTab(false);claimOwnership(uid,next.runId,()=>{setOtherTab(true);setRun(r=>({...r,paused:true}))});saveRun({...next,phase:'celebration',shotId:'A02'})};
const completedDialogue=lines&&run.dialogueIndex>=lines.length;
return <main className="rd-root" dir="rtl"><ScenePlayer shotId={run.shotId}><GameHud count={run.evidence.length+run.collectedDocs.length} onFile={()=>setFileOpen(true)} onPause={()=>commit(r=>({...r,paused:true}))} onExit={()=>{commit(r=>({...r,paused:true}));navigate('/app')}}/><div className="rd-content"><AnimatePresence mode="wait"><motion.div key={`${run.phase}-${run.shotId}`} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>
{run.phase==='cover'&&<section className="rd-cover"><img src={analystMark} alt="The Analyst"/><p>قضية جديدة</p><h1>قرار التكريم</h1><span>راجع الترشيح، وافحص الأدلة، ودافع عن قرارك.</span><ActionButton onClick={start}>{loadRun(uid)?'بدء جولة جديدة':'ابدأ الآن'}</ActionButton><img className="rd-imp" src={impLogo} alt="IMP"/></section>}
{line&&<DialoguePanel line={line as Line} index={run.dialogueIndex} total={lines.length} visible={run.visibleGraphemes} paused={run.paused} gender={profile?.gender??null} onVisible={n=>commit(r=>({...r,visibleGraphemes:n}))} onAdvance={advanceDialogue}/>} 
{run.phase==='briefing'&&completedDialogue&&<div className="rd-bottom-action"><ActionButton onClick={()=>setPhase('hub','A09')}>فتح الملف</ActionButton></div>}
{run.phase==='sales'&&completedDialogue&&<Panel title="تقرير المبيعات" onBack={()=>setPhase('hub')}><div className="rd-report"><div><b>فريق مروان</b><strong>9.5 مليون</strong><span>متوسط 95%</span></div><div><b>فريق محمود</b><strong>8.8 مليون</strong><span>متوسط 88%</span></div></div><div className="rd-actions"><ActionButton variant="secondary" onClick={()=>commit(r=>({...r,openedIndividualRecords:true,collectedDocs:[...new Set([...r.collectedDocs,'records'])],shotId:'A12'}))}>فتح كشف الأفراد</ActionButton><ActionButton onClick={()=>{saveDoc('sales');setPhase('hub')}}>حفظ في الملف</ActionButton></div></Panel>}
{run.phase==='hr'&&completedDialogue&&<Panel title="وثيقة معيار التكريم" onBack={()=>setPhase('hub')}><div className="rd-policy">يُعد الفرد محققًا لمعيار الأداء عند بلوغ 85% من مستهدفه أو أكثر. يراعي تكريم الأداء الجماعي انتشار تحقيق المعيار بين أفراد الفريق وتقارب نتائجهم.</div><ActionButton onClick={()=>{saveDoc('policy');setPhase('hub')}}>حفظ في الملف</ActionButton></Panel>}
{run.phase==='hub'&&<Panel title="مساحة التحقيق"><p className="rd-lead">اختار ترتيب التحقيق. كل المستندات تفضل محفوظة في ملف القضية.</p><div className="rd-destinations"><button onClick={()=>visit('sales')}><Users/><b>المبيعات</b><small>{run.collectedDocs.includes('sales')?'تم حفظ التقرير':'مكتب حسام'}</small></button><button onClick={()=>visit('hr')}><Building2/><b>الموارد البشرية</b><small>{run.collectedDocs.includes('policy')?'تم حفظ المعيار':'مكتب داليا'}</small></button><button onClick={()=>setPhase('workbench')}><FileSpreadsheet/><b>طاولة الفحص</b><small>{run.openedIndividualRecords?'الأدوات متاحة':'تحتاج كشف الأفراد'}</small></button></div>{run.evidence.length>=2&&run.collectedDocs.includes('policy')&&<ActionButton onClick={()=>setPhase('recommendation')}>تجهيز التوصية</ActionButton>}</Panel>}
{run.phase==='workbench'&&<Workbench available={run.openedIndividualRecords} saved={run.evidence} policy={run.collectedDocs.includes('policy')} onSave={id=>commit(r=>({...r,evidence:r.evidence.includes(id)?r.evidence:[...r.evidence,id]}))} onBack={()=>setPhase('hub')} onRecommendation={()=>setPhase('recommendation')}/>} 
{run.phase==='recommendation'&&<Recommendation team={run.draft.teamId} links={run.draft.links} evidence={run.evidence} onTeam={teamId=>commit(r=>({...r,draft:{...r.draft,teamId}}))} onLink={(i,l)=>commit(r=>{const links=[...r.draft.links];links[i]=l;return {...r,draft:{...r.draft,links}}})} onBack={()=>setPhase('workbench')} onSubmit={()=>commit(r=>({...r,submitted:{teamId:r.draft.teamId as TeamId,links:r.draft.links},phase:'meeting',shotId:'A18',meeting:{step:0,defense:null,followupUsed:false}}))}/>} 
{run.phase==='meeting'&&<Meeting run={run} onDefense={defense=>commit(r=>({...r,meeting:{...r.meeting,defense}}))} onReview={()=>commit(r=>({...r,phase:'workbench',shotId:'A15',reviewCount:r.reviewCount+1}))} onDecide={()=>commit(r=>{const outcome=evaluate(r);return {...r,outcome,phase:'resolution',shotId:outcome==='supported'?'A21':'A24'}})}/>} 
{run.phase==='resolution'&&<Panel title={run.outcome==='supported'?'اعتماد القرار':'الملف يحتاج مراجعة'}>{run.outcome==='supported'?<><p className="rd-resolution">نعتمد تكريم فريق محمود على معيار الأداء الجماعي.</p><p>المتوسط الذي بدأ منه الترشيح صحيح، لكنه لم يكن كافيًا وحده لهذا القرار.</p><ActionButton onClick={()=>setPhase('debrief')}>عرض الخلاصة</ActionButton></>:<><p className="rd-resolution">{run.outcome==='insufficient'?'ترشيحك ممكن يكون مناسب، لكن الملف لسه محتاج يثبت تحقيق المعيار وتقارب النتائج. ارجع كمّل المراجعة.':'أثبتّ النتيجة الأعلى، لكن لسه ما أثبتّش إنها الأنسب للتكريم الجماعي. التوصية تحتاج مراجعة.'}</p><div className="rd-actions"><ActionButton variant="secondary" onClick={()=>commit(r=>({...r,phase:'workbench',shotId:'A15',reviewCount:r.reviewCount+1,outcome:null}))}>مراجعة الملف</ActionButton><ActionButton onClick={()=>setPhase('debrief')}>عرض خلاصة التجربة</ActionButton></div></>}</Panel>}
{run.phase==='debrief'&&<Panel title="خلاصة التجربة"><ol className="rd-debrief"><li><b>الإجمالي</b><span>95% مقابل 88% — بداية صحيحة، مش الصورة كلها.</span></li><li><b>نتائج الأفراد</b><span>الوسيط يوضح المنتصف، ومقاييس التشتت توضح التقارب.</span></li><li><b>معيار 85%</b><span>4 من 10 مقابل 10 من 10.</span></li><li><b>التقارب</b><span>في الحالة دي، فريق محمود جمع تحقيق المطلوب وتقارب الأداء.</span></li></ol><div className="rd-actions"><ReplayButton onClick={()=>{clearRun(uid);start()}}/><ActionButton onClick={()=>navigate('/app')}>الألعاب</ActionButton></div></Panel>}
</motion.div></AnimatePresence></div></ScenePlayer>{fileOpen&&<CaseFile docs={run.collectedDocs} evidence={run.evidence} onClose={()=>setFileOpen(false)}/>} {(run.paused||otherTab)&&run.phase!=='cover'&&<PauseLayer otherTab={otherTab} onContinue={()=>commit(r=>({...r,paused:false}))} onTake={()=>{takeOwnership(uid,run.runId);setOtherTab(false);setRun(r=>({...r,paused:false}))}}/>}{!storageOk&&<div className="rd-storage-warning">الاستكمال بعد إغلاق الصفحة غير متاح حاليًا.</div>}</main>}
